### ISSUE TITLE
Tracking Testing Results for Brute Force Protection 1.1.0.

### ISSUE THREAD

**Issue by davitol** [owncloud/brute_force_protection#132]
Tested with oC 10.5 and tarball located here:https://github.com/owncloud/brute_force_protection/releases/download/v1.1.0RC2/brute_force_protection.tar.gz

## manual tests
set  threshold-time=15  fail-tolerance=4 ban-period=30

|Test scenario | expected result | result | comment |
|-----------------|--------------------|---------|-------------|
|enter invalid data in UI settings| data is not accepted | ✅  | |
|4 invalid logins but within 20 sec, correct login| login is possible | ✅| |
|block login, wait 30sec, correct login | login is possible again | ✅ | |
|block login, wait 30sec, 3 invalid logins, correct login | login is possible | ✅ | |
|block login, wait 30sec, 4 invalid logins, correct login | login is blocked | ✅| |
|block login, login with a **real** other IP but same user | login is possible | ✅ ||
|block login, login with a **real** other IP but same user, login again from the first IP | login is blocked | ✅||
|block login, force desktop client to resync | sync does work | ✅ |  |
|block login, force desktop client to resync, try correct login in browser | login blocked | ✅|  |
|set ban-period=600s, block user, invalid login, check message | correct no of min should be reported | ✅ ||
|set threshold-time=30 fail-tolerance=2 ban-period=3000, block user, wait 30sec (threshold-time), correct login| login is blocked |✅| |
|login with correct password, in different browser session block login for this user, refresh first session, try correct login in second session| login is blocked | ✅ | |

**Comment by davitol** [comment]
Changelog

### Added

- Add app icon - [#61](https://github.com/owncloud/brute_force_protection/issues/61)
- Added userfriendly text after too many login attempts - [#84](https://github.com/owncloud/brute_force_protection/issues/84)

### Fixed

- Fix documentation path - [#130](https://github.com/owncloud/brute_force_protection/issues/130)
- Protect public links password page - [#90](https://github.com/owncloud/brute_force_protection/issues/90)

**Comment by davitol** [comment]
# Changelog for 1.1.0 RC3

## Added

- [ ] Add app icon - [#61](https://github.com/owncloud/brute_force_protection/issues/61)
- [ ] Added userfriendly text after too many login attempts - [#84](https://github.com/owncloud/brute_force_protection/issues/84)

## Fixed
- [ ] Add CHANGELOG.md to release tarball - [#131](https://github.com/owncloud/brute_force_protection/pull/131)
- [ ] Fix documentation path - [#130](https://github.com/owncloud/brute_force_protection/issues/130)
- [ ] Protect public links password page - [#90](https://github.com/owncloud/brute_force_protection/issues/90)
- [ ] Internal Server Error on the password procted links after brute force protection ban -  [#134](https://github.com/owncloud/brute_force_protection/issues/134)
